version: "3"

services: 
  app:
    build: .
    command: yarn start
    ports:
      - "8080:8080"
    volumes: 
      - .:/usr/app
    depends_on: 
      - "mongoContainer"

  mongoContainer:
    image: mongo
    ports:
      - "6002:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: teste

