version: "3"

services: 
  app:
    build: .
    command: sh -c "yarn build && yarn start"
    ports:
      - "8080:8080"
    volumes: 
      - .:/usr/app
    depends_on: 
      - "mongoContainer"

  mongoContainer:
    image: mongo
    ports:
      - "27017:27017"


